version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
      - ./postgres-init/20_create-tables.sql:/docker-entrypoint-initdb.d/20_create-tables.sql
      - ${DB_BACKUP_LOCAL}:${DB_BACKUP_DOCKER}
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=16GB"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080